---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dapp-besu.fullname" . }}-secret
  labels:
    app: {{ template "dapp-besu.name" . }}
    chart: {{ template "dapp-besu.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  node_ingress_contract_address: {{ .Values.node_ingress_contract_address | b64enc }}
  account_ingress_contract_address: {{ .Values.account_ingress_contract_address | b64enc }}
  besu_node_perm_account: {{ .Values.besu_node_perm_account | b64enc }}
  besu_node_perm_key: {{ .Values.besu_node_perm_key | b64enc }}
  besu_node_perm_endpoint: {{ .Values.besu_node_perm_endpoint | b64enc }}
  network_id: {{ .Values.network_id | b64enc }}
  initial_whitelisted_nodes: {{ .Values.initial_whitelisted_nodes | b64enc }}
  initial_whitelisted_account: {{ .Values.initial_whitelisted_account | b64enc }}